### PR TITLE
Audio controls were overlapping the titles issue #181 solved

### LINKED ISSUE #181: Audio controls are overlapping the podcast list title when it is too long.
title-issue

Sugesstion:

title-issue-soltion

And this will applies to the podcast list titles as well.

title-overlap-darkmode

title-overlap-whitemode

### PR DESCRIPTION
**Pull request by dhara03**
Fixes #181

Regarding this issue, we decided to set max-width:95%, but that was not solving the issue in the podcast list title. So I set it to 94% and have given 98% in the searched podcast list title.

Desktop-screenshot (1)

### CODE REVIEW

**Comment by dellagustin** [comment]
Thank you @dhara03, I'll test today.

**Comment by dellagustin** [comment]
Hi @dhara03, I started testing and I noticed a side effect of adding the style `display: block` to the item title, there is a white space now below the title:
image
Do you think we can solve the issue without adding this space somehow? I know css is tricky...

About #177, the fix looks good.

One question about it though, do you have any idea why this only happens in the list of episodes of a podcast, but it does not happen for the list of podcasts nor the list of last episodes?

I inspected the styles, but could not find any meaningful difference between them, yet it happens.

Best Regards,
Guilherme.

**Comment by dhara03** [comment]
Hello @dellagustin , let's first start with issue #177 . To find the answer to it I checked all the templates thoroughly. 
Well, it's because of the table's default properties. Any table width is dependent on their data of TD. To explain this let me show you some SS. Here I have temporarily removed image from inspect elements from the searched podcast list. 
Desktop-screenshot (3)
In this case, we don't have a background color so we are not able to identify it at first whereas in episode list we have a background color so we can see it very clearly.

So to solve this issue we have to give table{ width:100%;}.

**Comment by dhara03** [comment]
Now let's talk about #181 , so yes that blank space is coming because of extra `<br>` in code. If we are giving display:block; it will automatically take the full width so the next div/span won't wrap the above line content. To solve this either we can remove that extra `<br>` or change the audio control CSS.
When I checked the structure of all templates I found that the episode list template structure is different from the podcast and podcast search list temp. Here are some SS to understand it.

Desktop-screenshot (6)

Desktop-screenshot (5)

Desktop-screenshot (4)

I'm suggesting to make the same structure as episode list structure and give CSS position: relative; to itemMenu. So in this way, we don't have to manipulate width of the title and remove max-width:95%;. If we won't change the structure and give position relative to controls it will look like below SS:

Desktop-screenshot (2)

So now what I'm thinking is, will commit these changes so that you can easily find out what changes I'm suggesting to you.  After that let me know if you find any issues. I would like to solve it.

**Comment by dellagustin** [comment]
Hi @dhara03 , thanks you for the explanations.
I did not remember the difference between the templates.
I tested the result of your last commit, it is looking good, I'll just offset the itemMenu one more pixel to the right, as the background still visible:
image

**Comment by dhara03** [comment]
Hello @dellagustin , I'm glad that you are satisfied with my explanations. Regarding itemMenu, I checked it in my last commit and set CSS according to that. May be hard refresh or removing cache will display the design properly. But anyway I again set one more pixel to right to avoid design issues on big screens.

**Comment by dellagustin** [comment]
Thank you!
It is merged, will be released on the next version.

**Comment by dhara03** [comment]
It is my great pleasure! 
Will wait for the next version and thanks for the update.

**Pull request merged**
